---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-doktor
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: node-doktor
  template:
    metadata:
      labels:
        app: node-doktor
      name: node-doktor
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      serviceAccountName: node-doktor
      containers:
      - image: artsy/node-doktor:latest
        imagePullPolicy: Always
        name: node-doktor
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "768Mi"
            cpu: "500m"
