---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-doktor
  namespace: kube-system
rules:
- nonResourceURLs:
  - "/version"
  - "/healthz"
  verbs: ["get"]
- apiGroups: [""]
  resources:
    - "events"
    - "pods"
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
    - "nodes"
  verbs: ["get", "update"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-doktor
  namespace: kube-system
automountServiceAccountToken: true

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-doktor
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: node-doktor
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: node-doktor
  apiGroup: rbac.authorization.k8s.io

